-- Migración para crear la tabla de catálogo del programa anual
CREATE TABLE IF NOT EXISTS public.programa_anual_catalogo (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    descripcion TEXT NOT NULL UNIQUE,
    marco_legal TEXT NOT NULL,
    jurisdiccion VARCHAR(100) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar RLS
ALTER TABLE public.programa_anual_catalogo ENABLE ROW LEVEL SECURITY;

-- Política de lectura pública
CREATE POLICY "Permitir lectura publica de programa_anual_catalogo" ON public.programa_anual_catalogo
    FOR SELECT TO public USING (true);

-- Insertar catálogo de actividades
INSERT INTO public.programa_anual_catalogo (descripcion, marco_legal, jurisdiccion) VALUES
('Análisis bacteriológico de agua de consumo humano (Semestral)', 'Ley 19.587 - Dec. 351/79 - Res. 905/15', 'Nacional'),
('Análisis fisicoquímico de agua de consumo humano (Anual)', 'Ley 19.587 - Dec. 351/79 - Res. 905/15', 'Nacional'),
('Análisis mensual de efluentes líquidos (CTM)', 'Dec. 674/89', 'Nacional'),
('Canon por uso de agua y tasa de inspección de funcionamiento y control de efluentes (ADA)', 'Ley 12257 - Res. ADA 943/17', 'Prov. Bs.As.'),
('Certificado de aptitud ambiental (CAA)', 'Ley 11459 - Dec. 531/19 - Res. OPDS 565/19', 'Prov. Bs.As.'),
('Certificado de aptitud técnica y de seguridad (GLP)', 'Res. S.E. 1097/15', 'Nacional'),
('Control trimestral de Extintores (verificación visual de la presión por observación del manómetro, de partes mecánicas, válvula, precinto, marbete, manga, etc.)', 'Ley 19.587 - Dec. 351/79 - Res. 905/15', 'Nacional'),
('Certificado de instalaciónes de almacenamiento de hidrocarburos (hermeticidad, superficie y protección catódica)', 'Res. S.E. 1102/04; Res. S.E. 419/93; Res. S.E. 404/94', 'Nacional'),
('Confeccionar / actualizar el diagrama de procesos y distribución en planta con indicación de todas las maquinarias señalando las áreas que presenten o puedan presentar riesgos en materia de Higiene y Seguridad en el Trabajo.', 'Dec. 351/79 - Res. 905/15', 'Nacional'),
('Confeccionar / actualizar el Plan de Evacuación', 'Dec. 351/79; Res. 905/15', 'Nacional'),
('Confeccionar el manual de procedimientos del Servicio de Higiene y Seguridad', 'Res. 905/15', 'Nacional'),
('Confeccionar y dar seguimiento al Plan Acciones Correctivas', 'Res. 905/15', 'Nacional'),
('Confeccionar / actualizar los Planos generales de evacuación, con vías de escape y detalle de los servicios de prevención y lucha contra incendio', 'Dec. 351/79 - Res. 905/15 - Ley 5920', 'C.A.B.A.'),
('Control hidrogeologico de pozos de explotacion de agua / freáticos', 'Res. ADA 2222/19', 'Prov. Bs.As.'),
('Controlar y verificar la alimentación provista por el empleador', 'Res. 905/15', 'Nacional'),
('Controlar y verificar la exposición a Carga Térmica - Estrés por calor', 'Dec. 351/79 - Res. 30/23', 'Nacional'),
('Controlar y verificar la intensidad mínima de Iluminación, sobre el plano de trabajo', 'Dec. 351/79 - Res. 84/12 - Res. 905/15', 'Nacional'),
('Controlar y verificar la Puesta a tierra y continuidad de masas', 'Dec. 351/79 - Res. 900/15 - Res. 905/15', 'Nacional'),
('Controlar y verificar la realización de los Exámenes médicos periódicos', 'Ley 24557 - Dec. 1338/96 - Res. 905/15', 'Nacional'),
('Controlar y verificar la ventilación mínima de los locales', 'Dec. 351/79', 'Nacional'),
('Controlar y verificar los niveles de exposicion a Contaminantes Fisicos (CONDICIONES HIGROTERMICAS)', 'Dec. 351/79 - Res. 295/03 - Res. 886/15 - Res. 905/15', 'Nacional'),
('Controlar y verificar los niveles de exposicion a Contaminantes Físicos (LÁSERES )', 'Dec. 351/79 - Res. 295/03 - Res. 905/15', 'Nacional'),
('Controlar y verificar los niveles de exposicion a Contaminantes Físicos (RADIACIONES IONIZANTES )', 'Dec. 351/79 - Res. 295/03 - Res. 905/15', 'Nacional'),
('Controlar y verificar los niveles de exposicion a Contaminantes Físicos (RADIACIONES NO IONIZANTES )', 'Dec. 351/79 - Res. 295/03 - Res. 905/15', 'Nacional'),
('Controlar y verificar los niveles de exposicion a Contaminantes Físicos (RUIDO)', 'Dec. 351/79 - Res. 85/12 - Res. 301/11 - Res. 905/15', 'Nacional'),
('Controlar y verificar los niveles de exposicion a Contaminantes Físicos (VIBRACIONES)', 'Dec. 351/79 - Res. 295/03 - Res. 886/15 - Res. 905/15', 'Nacional'),
('Controlar y verificar los niveles de exposicion a Contaminantes Químicos en el aire', 'Dec. 351/79 - Res. 861/15 - Res. 905/15', 'Nacional'),
('Corroborar el cumplimiento de la normativa en Seguridad y Salud en el Trabajo (Matríz de cumplimiento legal)', 'Res. 905/15', 'Nacional'),
('Corroborar el cumplimiento de la normativa en Seguridad y Salud en el Trabajo de las empresas contratistas de obras y servicios', 'Res. 905/15', 'Nacional'),
('Declaración Jurada anual de Residuos Especiales y renovación del registro de generadores de residuos especiales industriales (según ley 11720 y normativa vigente MAyDS).', 'Ley 11720', 'Prov. Bs.As.'),
('Declaración jurada de efluentes líquidos (INA)', 'Dec. 674/89', 'Nacional'),
('Declaración Jurada anual de Residuos Industriales No Especiales (RINE)', 'Ley 11720 - Res. 60/26', 'Prov. Bs.As.'),
('Declaración jurada para informar la presencia de Sustancias y Agentes Cancerígenos (S.V.C.C.)', 'Res. 81/19', 'Nacional'),
('Definir la política del establecimiento en materia de Seguridad y Salud en el Trabajo', 'Dec. 1338/96 - Res. 905/15', 'Nacional'),
('Efectuar la investigación y elaborar estadísticas, de accidentes de trabajo y enfermedades profesionales', 'Res. 905/15', 'Nacional'),
('Elaborar el Programa Anual de Capacitación en materia de Higiene y Seguridad en el Trabajo', 'Dec. 351/79 - Res. 905/15', 'Nacional'),
('Elaborar el Programa de Higiene y Seguridad en el Trabajo', 'Dec. 351/79 - Res. 905/15', 'Nacional'),
('Evaluar los Riesgos Ergonómicos', 'Res. 295/03 - Res. 886/15 - Res. 3345/15 - Res. 905/15', 'Nacional'),
('Habilitación / Renovación de los Aparatos Sometidos a Presión', 'Dec. 351/79 - Ley 5920 - Res. 231/96 (Prov. de Bs.As.) - Res. 1126/07 (Prov. de Bs.As.)', 'Prov. Bs.As.'),
('Identificar y realizar evaluación inicial de los Factores de Riesgo Ergonómico', 'Res. 295/03 - Res. 886/15 - Res. 3345/15 - Res. 905/15', 'Nacional'),
('Informe trimestral del RENPRE', 'Dec. Nac. 593/19 - Dec. Nac. 1095/96', 'Nacional'),
('Inspección anual, Habilitación / renovación de A.S.P.', 'Res. SPA 231/96 - Res. SPA 1126/07 - Res. SPA 129/97 - Res. SPA 529/98', 'Prov. Bs.As.'),
('Inspección Visual de Instalaciones Eléctricas (trimestral)', 'Dec. 351/79', 'Nacional'),
('Licencia de emisiones gaseosas (LEGA)', 'Dec. 1074/19 - Res. OPDS 559/19', 'Prov. Bs.As.'),
('Limpieza de Campanas, Conductos y Afines (Bimestral)', 'Ley 6100 - Ley 6438 - Res. 83/24 - Disp. 913/25', 'C.A.B.A.'),
('Limpieza de Campanas, Conductos y Afines (Cuatrimestral)', 'Ley 6100 - Ley 6438 - Res. 83/24 - Disp. 913/25', 'C.A.B.A.'),
('Limpieza de Campanas, Conductos y Afines (Semestral)', 'Ley 6100 - Ley 6438 - Res. 83/24 - Disp. 913/25', 'C.A.B.A.'),
('Limpieza de Campanas, Conductos y Afines (Trimestral)', 'Ley 6100 - Ley 6438 - Res. 83/24 - Disp. 913/25', 'C.A.B.A.'),
('Limpieza de tanque de agua para consumo humano', 'Ley 19587 - Dec. 351/79 - CAA', 'Nacional'),
('Monitoreo de efluentes gaseosos (chimeneas + clidad de aire)', 'Dec. 1074/19 - Res. OPDS 559/19', 'Prov. Bs.As.'),
('Permiso de Aptitud Hidráulica de Obra (ADA)', 'Res. ADA 2222/19', 'Prov. Bs.As.'),
('Permiso de Explotación del Recurso Hídrico Subterráneo', 'Res. ADA 2222/19', 'Prov. Bs.As.'),
('Permiso de vuelco de efluentes (ADA)', 'Res. ADA 2222/19', 'Prov. Bs.As.'),
('Prefactibilidad Hídrica (ADA)', 'Res. ADA 2222/19', 'Prov. Bs.As.'),
('Programa de mantenimiento preventivo y correctivo de instalaciones eléctricas', 'Dec. 351/79', 'Nacional'),
('Programa de mantenimiento preventivo y correctivo de máquinas y equipos (Aparatos para izar, Ascensores y Montacargas, Calderas y recipientes a presión, etc.)', 'Ley 19587 - Dec. 170/96', 'Nacional'),
('Programa de mantenimiento preventivo y correctivo de sistema de extracción, ductos cañerías, filtros, campanas, etc.', 'Ley 19587 - Dec. 170/96', 'Nacional'),
('Programa de Seguridad (Res. 51/97; Res. 35/98; Res. 319/99)', 'Dec. 911/96 - Res. 231/96 - Res. 51/97 - Res. 35/98 - Res. 319/99 - Res. 550/11 - Res. 552/01', 'Nacional'),
('Promover la conformación del Comité Mixto de Higiene y Seguridad en el Trabajo', 'Dec. 351/79 - Res. 905/15 - Ley 14408 (Prov. de Bs.As.)', 'Prov. Bs.As.'),
('Promover las reuniones mensuales del Comité Mixto de Higiene y Seguridad en el Trabajo', 'Dec. 351/79 - Res. 905/15 - Ley 14408 (Prov. de Bs.As.)', 'Prov. Bs.As.'),
('Realizar actividades de capacitación, según cronograma de capacitación anual', 'Dec. 351/79 - Res. 905/15', 'Nacional'),
('Realizar actividades de capacitación, según cronograma de capacitación anual (Operación segura de autoelevadores)', 'Dec. 351/79 - Res. 905/15', 'Nacional'),
('Realizar actividades de capacitación, según cronograma de capacitación anual (Práctica de Brigadistas o Equipo de Primera Intervención)', 'Dec. 351/79 - Res. 905/15', 'Nacional'),
('Realizar actividades de capacitación, según cronograma de capacitación anual (Primeros auxilios y Reanimación Cardio Pulmonar)', 'Dec. 351/79 - Res. 905/15', 'Nacional'),
('Realizar seguimiento de elevadores, montacargas, etc.', 'Dec. 351/79', 'Nacional'),
('Realizar simulacro de derrame de producto químico', 'Dec. 351/79 - Res. 905/15', 'Nacional'),
('Realizar simulacro de evacuación', 'Dec. 351/79 - Ley 5920 - Res. 905/15', 'C.A.B.A.'),
('Realizar/ renovar aplicación de retardante de llamas - tratamiento ignífugo', 'Dec. 351/79', 'Nacional'),
('Registro de Instalaciones Térmicas (RIT)', 'Código de Edificación (Ley 6100 y Ley 6438) - Res. 412/19', 'C.A.B.A.'),
('Relevamiento de Agentes de Riesgos', 'Ley 24557', 'Nacional'),
('Relevamiento General de Riesgos Laborales', 'Res. 463/09', 'Nacional'),
('Relevar y confeccionar / actualizar el informe de Anti Siniestralidad', 'Dec. 351/79', 'Nacional'),
('Relevar y confeccionar / actualizar el informe de Carga de Fuego', 'Dec. 351/79', 'Nacional'),
('Relevar y confeccionar / actualizar el Mapa de Riesgos Laborales', 'Dec. 1338/96 - Res. 905/15', 'Nacional'),
('Relevar y confeccionar / actualizar el Sistema de Autoprotección', 'Ley 5920', 'C.A.B.A.'),
('Relevar y confeccionar / actualizar la Matriz de identificación de peligros y evaluación de riesgos', 'Dec. 351/79 - Res. 905/15', 'Nacional'),
('Registro de Campanas, Conductos y Afines', 'Ley 6100 - Ley 6438 - Res. 83/24 - Disp. 913/25', 'C.A.B.A.'),
('Renovación anual del RENPRE (Sedronar)', 'Dec. Nac. 593/19 - Dec. Nac. 1095/96', 'Nacional'),
('Ruidos molestos al vecindario (según Norma IRAM 4062; Res. SPA 159/96; Resolución SPA 94/02)', 'Norma IRAM 4062; Res. SPA 159/96; Resolución SPA 94/02', 'Prov. Bs.As.'),
('Seguro Ambiental Obligatorio', 'Ley 25675 - Dec. 2090/10', 'Nacional'),
('Visitar y relevar los puestos de trabajo, según lo ameriten los riesgos propios de la actividad', 'Dec. 1338/96 - Res. 905/15', 'Nacional');
