-- 20260711000000_create_zonas_cuerpo_afectadas.sql
-- Creación de la tabla de catálogo de Zonas del Cuerpo Afectadas

CREATE TABLE IF NOT EXISTS public.zonas_cuerpo_afectadas (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    nombre TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.zonas_cuerpo_afectadas ENABLE ROW LEVEL SECURITY;

-- Política de lectura pública para cualquier usuario autenticado o anónimo
CREATE POLICY "Permitir lectura publica de zonas_cuerpo_afectadas" ON public.zonas_cuerpo_afectadas
    FOR SELECT TO public USING (true);

-- Insertar catálogo de zonas del cuerpo afectadas
INSERT INTO public.zonas_cuerpo_afectadas (nombre) VALUES
('Abdomen (pared abdominal)'),
('Abdomen y Miembros Inferiores'),
('Abdomen y Miembros Superiores'),
('Antebrazo'),
('Aorta'),
('Aparato cardiovascular en general'),
('Aparato Cardiovascular y Digestivo'),
('Aparato Cardiovascular y Genitourinario'),
('Aparato Cardiovascular y Respiratorio'),
('Aparato Cardiovascular y Sistema Nervioso'),
('Aparato digestivo en general'),
('Aparato genitourinario en general'),
('Aparato Psíquico'),
('Aparato respiratorio en general'),
('Aparato Respiratorio y Digestivo'),
('Aparato Respiratorio y Piel'),
('Aparato Vestibular (incluye la rama Vestibular del Nervio Auditivo)'),
('Arterias y Venas de la Cabeza'),
('Arterias y Venas de Miembros Inferiores'),
('Arterias y Venas de Miembros Superiores'),
('Arterias y Venas del Abdomen'),
('Arterias y Venas del Cuello'),
('Arterias y Venas del Tórax'),
('Bazo'),
('Boca (con inclusión de labios, dientes y lengua)'),
('Brazo (Incluyendo articulación del húmero)'),
('Bronquios'),
('Bulbo'),
('Cabeza y Abdomen'),
('Cabeza y Cuello'),
('Cabeza y Miembros Inferiores'),
('Cabeza y Miembros Superiores'),
('Cabeza y Tórax'),
('Cabeza, ubicaciones múltiples'),
('Cadera'),
('Cara (ubicación no clasificada en otros epígrafes)'),
('Cava'),
('Cerebelo'),
('Cerebro'),
('Codo'),
('Columna Vertebral y Médula Espinal'),
('Conducto Torácico'),
('Corazón'),
('Cuello'),
('Dedos de las manos'),
('Dedos de los pies'),
('Esófago'),
('Estomago'),
('Faringe'),
('Ganglios'),
('Hígado'),
('Hipófisis'),
('Hombro (con inclusión de clavícula, omóplato y axila)'),
('Intestino Delgado'),
('Intestino Grueso'),
('Laringe'),
('Mamas'),
('Mano (con excepción de los dedos solos)'),
('Medula espinal'),
('Medula ósea'),
('Miembro inferior, ubicaciones múltiples'),
('Miembro superior, ubicaciones múltiples'),
('Miembros Inferiores'),
('Miembros Superiores'),
('Miembros Superiores e Inferiores'),
('Muñeca'),
('Muslo'),
('Nariz'),
('Nervios Craneanos'),
('Nervios Periféricos de Miembro Inferior'),
('Nervios Periféricos de Miembro Superior'),
('Nervios Periféricos del Tronco'),
('Oído (incluye Oído medio e interno y Nervio auditivo)'),
('Ojos (con inclusión de los Párpados, la órbita y del nervio óptico)'),
('Ovarios'),
('Pabellón Auricular (incluye Conducto Auditivo externo)'),
('Páncreas'),
('Pared abdominal y órganos internos'),
('Pared torácica y órganos internos (incluye Mediastino)'),
('Parótidas'),
('Pelvis'),
('Pene'),
('Pie (con excepción de los dedos solos)'),
('Piel'),
('Pierna'),
('Pineal'),
('Pleura'),
('Plexos nerviosos'),
('Próstata'),
('Protuberancia'),
('Pulmones'),
('Recto y Ano'),
('Región cervical (columna vertebral y músculos adyacentes)'),
('Región craneana (cráneo, cuero cabelludo)'),
('Región dorsal (columna vertebral y músculos adyacentes)'),
('Región lumbosacra (columna vertebral y músculos adyacentes)'),
('Riñón'),
('Rodilla'),
('Senos Frontales'),
('Senos Paranasales'),
('Sistema Endócrino en general'),
('Sistema Hematopoyético en general'),
('Sistema Linfático en general'),
('Sistema nervioso en general'),
('Sistema Nervioso y Piel'),
('Sublinguales'),
('Submaxilares'),
('Suprarrenal'),
('Testículos'),
('Tiroides'),
('Tobillo'),
('Tórax (costillas, esternón, articulación acromioclavicular)'),
('Tórax y Abdomen'),
('Tórax y Miembros Inferiores'),
('Tórax y Miembros Superiores'),
('Traquea'),
('Trompa de Falopio'),
('Tronco, ubicaciones múltiples'),
('Ubicaciones múltiples (más de dos zonas del cuerpo no listadas)'),
('Uréter'),
('Uretra'),
('Útero'),
('Vagina'),
('Vejiga'),
('Vesícula Biliar y Vías Biliares'),
('Vulva'),
('No Aplica')
ON CONFLICT (nombre) DO NOTHING;

-- Notificar recarga de caché a PostgREST
NOTIFY pgrst, 'reload schema';
