// src/app/[tenant-slug]/protocolos/iluminacion/utils/tablasAnexoIV.js
/**
 * Anexo IV - Capítulo 12: Iluminación y Color - Decreto 351/79
 * Basadas en Norma IRAM-AADL J 20-06
 */

export const TABLA_1_ILUMINACION = [
  {
    clase: 'Visión ocasional solamente',
    luxTexto: '100',
    luxMin: 100,
    ejemplos: 'Para permitir movimientos seguros, por ejemplo: en lugares de poco tránsito; sala de calderas; depósito de materiales voluminosos y otros.'
  },
  {
    clase: 'Tareas intermitentes ordinarias y fáciles, con contrastes fuertes',
    luxTexto: '100 a 300',
    luxMin: 100,
    ejemplos: 'Trabajos simples, intermitentes y mecánicos; inspección general y contado de partes de stock; colocación de maquinaria pesada.'
  },
  {
    clase: 'Tarea moderadamente crítica y prolongada, con detalles medianos',
    luxTexto: '300 a 750',
    luxMin: 300,
    ejemplos: 'Trabajos medianos, mecánicos y manuales; inspección y montaje; trabajos comunes de oficina, tales como: lectura, escritura y archivo.'
  },
  {
    clase: 'Tareas severas y prolongadas y de poco contraste',
    luxTexto: '750 a 1500',
    luxMin: 750,
    ejemplos: 'Trabajos finos, mecánicos y manuales; montajes e inspección; pintura extrafina; sopleteado; costura de ropa oscura.'
  },
  {
    clase: 'Tareas muy severas y prolongadas, con detalles minuciosos o muy poco contraste',
    luxTexto: '1500 a 3000',
    luxMin: 1500,
    ejemplos: 'Montaje e inspección de mecanismos delicados; fabricación de herramientas y matrices; inspección con calibrador; trabajo de molienda fina.'
  },
  {
    clase: 'Tareas muy severas y prolongadas, con detalles minuciosos o muy poco contraste (Relojería)',
    luxTexto: '3000',
    luxMin: 3000,
    ejemplos: 'Trabajo fino de relojería y reparación.'
  },
  {
    clase: 'Tareas excepcionales, difíciles o importantes',
    luxTexto: '5000 a 10000',
    luxMin: 5000,
    ejemplos: 'Casos especiales, como por ejemplo: iluminación del campo operatorio en una sala de cirugía.'
  }
];

export const TABLA_2_ILUMINACION = [
  // Vivienda
  { grupo: 'Vivienda', subtitulo: 'Baño', tarea: 'Iluminación general', lux: 100 },
  { grupo: 'Vivienda', subtitulo: 'Baño', tarea: 'Iluminación localizada sobre espejos', lux: 200 },
  { grupo: 'Vivienda', subtitulo: 'Dormitorio', tarea: 'Iluminación general', lux: 200 },
  { grupo: 'Vivienda', subtitulo: 'Dormitorio', tarea: 'Iluminación localizada: cama, espejo', lux: 200 },
  { grupo: 'Vivienda', subtitulo: 'Cocina', tarea: 'Iluminación sobre la zona de trabajo: cocina, pileta, mesada', lux: 200 },

  // Centros Comerciales
  { grupo: 'Centros Comerciales de Mediana Importancia', subtitulo: '', tarea: 'Iluminación general', lux: 500 },
  { grupo: 'Centros Comerciales de Mediana Importancia', subtitulo: '', tarea: 'Iluminación general en grandes locales', lux: 1000 },
  { grupo: 'Centros Comerciales de Mediana Importancia', subtitulo: '', tarea: 'Depósito de mercaderías', lux: 300 },

  // Hoteles
  { grupo: 'Hoteles', subtitulo: 'Circulaciones', tarea: 'Pasillos, palier y ascensor', lux: 100 },
  { grupo: 'Hoteles', subtitulo: 'Circulaciones', tarea: 'Hall de entrada', lux: 300 },
  { grupo: 'Hoteles', subtitulo: 'Circulaciones', tarea: 'Escalera', lux: 100 },
  { grupo: 'Hoteles', subtitulo: 'Local para ropa blanca', tarea: 'Iluminación general', lux: 200 },
  { grupo: 'Hoteles', subtitulo: 'Local para ropa blanca', tarea: 'Costura', lux: 400 },
  { grupo: 'Hoteles', subtitulo: '', tarea: 'Lavandería', lux: 100 },
  { grupo: 'Hoteles', subtitulo: '', tarea: 'Vestuarios', lux: 100 },
  { grupo: 'Hoteles', subtitulo: '', tarea: 'Sótano, bodegas', lux: 70 },
  { grupo: 'Hoteles', subtitulo: '', tarea: 'Depósitos', lux: 100 },

  // Garajes y Estaciones de Servicio
  { grupo: 'Garajes y Estaciones de Servicio', subtitulo: '', tarea: 'Iluminación general', lux: 100 },
  { grupo: 'Garajes y Estaciones de Servicio', subtitulo: '', tarea: 'Gomería', lux: 200 },

  // Oficinas
  { grupo: 'Oficinas', subtitulo: '', tarea: 'Halls para el público', lux: 200 },
  { grupo: 'Oficinas', subtitulo: '', tarea: 'Contaduría, tabulaciones, teneduría de libros, operaciones bursátiles, lectura de reproducciones, bosquejos rápidos', lux: 500 },
  { grupo: 'Oficinas', subtitulo: '', tarea: 'Trabajo general de oficinas, lectura de buenas reproducciones, lectura, transcripción de escritura a mano en papel y lápiz ordinario, archivo, índices de referencia, distribución de correspondencia', lux: 500 },
  { grupo: 'Oficinas', subtitulo: '', tarea: 'Trabajos especiales de oficina, por ejemplo sistema de computación de datos', lux: 750 },
  { grupo: 'Oficinas', subtitulo: '', tarea: 'Sala de conferencias', lux: 300 },
  { grupo: 'Oficinas', subtitulo: '', tarea: 'Circulación', lux: 200 },

  // Bancos
  { grupo: 'Bancos', subtitulo: '', tarea: 'Iluminación general', lux: 500 },
  { grupo: 'Bancos', subtitulo: '', tarea: 'Sobre zonas de escritura y cajas', lux: 750 },
  { grupo: 'Bancos', subtitulo: '', tarea: 'Sala de caudales', lux: 500 },

  // Industrias Alimenticias
  { grupo: 'Industrias Alimenticias', subtitulo: 'Mataderos municipales', tarea: 'Recepción', lux: 50 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Corrales', tarea: 'Inspección', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Corrales', tarea: 'Permanencia', lux: 50 },
  { grupo: 'Industrias Alimenticias', subtitulo: '', tarea: 'Matanza', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: '', tarea: 'Deshollado', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: '', tarea: 'Escaldado', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: '', tarea: 'Evisceración', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: '', tarea: 'Inspección', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: '', tarea: 'Mostradores de venta', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Frigoríficos', tarea: 'Cámaras frías', lux: 50 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Frigoríficos', tarea: 'Salas de máquinas', lux: 150 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de carne', tarea: 'Corte, deshuesado, elección', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de carne', tarea: 'Cocción', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de carne', tarea: 'Preparación de patés, envasado', lux: 150 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de carne', tarea: 'Esterilización', lux: 150 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de carne', tarea: 'Inspección', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de carne', tarea: 'Preparación de embutidos', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de pescado y mariscos', tarea: 'Recepción', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de pescado y mariscos', tarea: 'Lavado y preparación', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de pescado y mariscos', tarea: 'Cocción', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de pescado y mariscos', tarea: 'Envasado', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de pescado y mariscos', tarea: 'Esterilización', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de pescado y mariscos', tarea: 'Inspección', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de pescado y mariscos', tarea: 'Embalaje', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de pescado y mariscos', tarea: 'Preparación de pescado ahumado', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de pescado y mariscos', tarea: 'Secado', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de pescado y mariscos', tarea: 'Cámara de secado', lux: 50 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de verduras y frutas', tarea: 'Recepción y selección', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de verduras y frutas', tarea: 'Preparación mecanizada', lux: 150 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de verduras y frutas', tarea: 'Envasado', lux: 150 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de verduras y frutas', tarea: 'Esterilización', lux: 150 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de verduras y frutas', tarea: 'Cámara de procesado', lux: 50 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de verduras y frutas', tarea: 'Inspección', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Conservas de verduras y frutas', tarea: 'Embalaje', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Molinos harineros', tarea: 'Depósito de granos', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Molinos harineros', tarea: 'Limpieza', lux: 150 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Molinos harineros', tarea: 'Molienda y tamizado', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Molinos harineros', tarea: 'Clasificación de harinas', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Molinos harineros', tarea: 'Colocación de bolsas', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Silos', tarea: 'Zona de recepción', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Silos', tarea: 'Circulaciones', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Silos', tarea: 'Sala de comando', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Panaderías', tarea: 'Depósito de harinas', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Amasado', tarea: 'Sobre artesas', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Cocción', tarea: 'Iluminación general', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Cocción', tarea: 'Delante de los hornos', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Fábrica de bizcochos', tarea: 'Depósito de harinas', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Fábrica de bizcochos', tarea: 'Local de elaboración', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Fábrica de bizcochos', tarea: 'Inspección', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Fábrica de bizcochos', tarea: 'Depósito del producto elaborado', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Pastas alimenticias', tarea: 'Depósito de harinas', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Pastas alimenticias', tarea: 'Local de elaboración', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Pastas alimenticias', tarea: 'Secado', lux: 50 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Pastas alimenticias', tarea: 'Inspección y empaquetado', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Torrefacción de café', tarea: 'Depósito', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Torrefacción de café', tarea: 'Torrefacción', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Torrefacción de café', tarea: 'Inspección y empaquetado', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Fábrica de chocolate', tarea: 'Depósito', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Fábrica de chocolate', tarea: 'Preparación de chocolate', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Fábrica de chocolate', tarea: 'Preparación de cacao en polvo', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Fábrica de chocolate', tarea: 'Inspección y empaquetado', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Usinas pasteurizadoras', tarea: 'Recepción y control de materia prima', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Usinas pasteurizadoras', tarea: 'Pasteurización', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Usinas pasteurizadoras', tarea: 'Envasado', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Usinas pasteurizadoras', tarea: 'Encajonado', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Usinas pasteurizadoras', tarea: 'Laboratorio', lux: 600 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Fábrica de derivados lácteos', tarea: 'Elaboración', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Fábrica de derivados lácteos', tarea: 'Cámaras frías', lux: 50 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Fábrica de derivados lácteos', tarea: 'Sala de máquinas', lux: 150 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Fábrica de derivados lácteos', tarea: 'Depósitos de quesos', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Fábrica de derivados lácteos', tarea: 'Envasado', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Vinos y bebidas alcohólicas', tarea: 'Recepción de materia prima', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Vinos y bebidas alcohólicas', tarea: 'Local de elaboración', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Local de cubas', tarea: 'Circulaciones', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Local de cubas', tarea: 'Curado y embotellado', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Embotellado', tarea: 'Iluminación general', lux: 150 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Embotellado', tarea: 'Embalaje', lux: 150 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Cervezas y malterías', tarea: 'Depósito', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Cervezas y malterías', tarea: 'Preparación de la malta', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Cervezas y malterías', tarea: 'Trituración y colocación de la malta en bolsas', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Cervezas y malterías', tarea: 'Elaboración', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Cervezas y malterías', tarea: 'Locales de fermentación', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Fábrica de azúcar', tarea: 'Recepción de materia prima', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Elaboración del azúcar', tarea: 'Iluminación general', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Elaboración del azúcar', tarea: 'Turbinas de trituración', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Elaboración del azúcar', tarea: 'Almacenamiento de azúcar', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Elaboración del azúcar', tarea: 'Embolsado', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Manómetros, niveles', tarea: 'Iluminación localizada', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: '', tarea: 'Sala de máquinas', lux: 150 },
  { grupo: 'Industrias Alimenticias', subtitulo: '', tarea: 'Tableros de distribución y laboratorios', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Refinerías', tarea: 'Iluminación general', lux: 100 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Refinerías', tarea: 'Amasado sobre cada turbina', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Refinerías', tarea: 'Molienda sobre la máquina', lux: 300 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Refinerías', tarea: 'Empaque', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Cocción y preparación de pastas', tarea: 'Iluminación general', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Cocción y preparación de pastas', tarea: 'Iluminación localizada', lux: 400 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Elaboración y terminación', tarea: 'Iluminación general', lux: 200 },
  { grupo: 'Industrias Alimenticias', subtitulo: 'Elaboración y terminación', tarea: 'Iluminación localizada', lux: 400 },

  // Metalúrgica
  { grupo: 'Metalúrgica', subtitulo: 'Fundiciones', tarea: 'Depósito de barras y lingotes', lux: 100 },
  { grupo: 'Metalúrgica', subtitulo: 'Transporte, tamizado y mezcla', tarea: 'Transportadoras, elevadores, trituradores y tamices', lux: 100 },
  { grupo: 'Metalúrgica', subtitulo: 'Fabricación de noyos', tarea: 'Fino', lux: 300 },
  { grupo: 'Metalúrgica', subtitulo: 'Fabricación de noyos', tarea: 'Grueso', lux: 200 },
  { grupo: 'Metalúrgica', subtitulo: '', tarea: 'Depósito de placas modelos', lux: 100 },
  { grupo: 'Metalúrgica', subtitulo: '', tarea: 'Zona de pesado de cargas', lux: 100 },
  { grupo: 'Metalúrgica', subtitulo: 'Taller de moldeo', tarea: 'Iluminación general', lux: 250 },
  { grupo: 'Metalúrgica', subtitulo: 'Taller de moldeo', tarea: 'Iluminación localizada en moldes', lux: 500 },
  { grupo: 'Metalúrgica', subtitulo: 'Taller de moldeo', tarea: 'Llenado de moldes', lux: 200 },
  { grupo: 'Metalúrgica', subtitulo: 'Taller de moldeo', tarea: 'Desmolde', lux: 100 },
  { grupo: 'Metalúrgica', subtitulo: 'Acerías', tarea: 'Depósito de minerales y carbón', lux: 100 },
  { grupo: 'Metalúrgica', subtitulo: 'Acerías', tarea: 'Zona de colado', lux: 100 },
  { grupo: 'Metalúrgica', subtitulo: 'Acerías', tarea: 'Trenes de laminación', lux: 200 },
  { grupo: 'Metalúrgica', subtitulo: 'Fabricación de alambre', tarea: 'Laminación en frío', lux: 300 },
  { grupo: 'Metalúrgica', subtitulo: 'Fabricación de alambre', tarea: 'Laminación en caliente', lux: 200 },
  { grupo: 'Metalúrgica', subtitulo: 'Mecánica general', tarea: 'Depósito de materiales', lux: 100 },
  { grupo: 'Metalúrgica', subtitulo: 'Inspección y control de calidad', tarea: 'Trabajo grueso: contar, control grueso de objetos de depósito', lux: 300 },
  { grupo: 'Metalúrgica', subtitulo: 'Inspección y control de calidad', tarea: 'Trabajo mediano: ensamble previo', lux: 600 },
  { grupo: 'Metalúrgica', subtitulo: 'Inspección y control de calidad', tarea: 'Trabajo fino: dispositivos de calibración, mecánica de precisión, instrumentos', lux: 1200 },
  { grupo: 'Metalúrgica', subtitulo: 'Inspección y control de calidad', tarea: 'Trabajo muy fino: calibración e inspección de piezas de montaje pequeñas', lux: 2000 },
  { grupo: 'Metalúrgica', subtitulo: 'Inspección y control de calidad', tarea: 'Trabajo minucioso: instrumentos muy pequeños', lux: 3000 },
  { grupo: 'Metalúrgica', subtitulo: 'Talleres de montaje', tarea: 'Trabajo grueso: montaje de máquinas pesadas', lux: 200 },
  { grupo: 'Metalúrgica', subtitulo: 'Talleres de montaje', tarea: 'Trabajo mediano: montaje de máquinas, chasis de vehículos', lux: 400 },
  { grupo: 'Metalúrgica', subtitulo: 'Talleres de montaje', tarea: 'Trabajo fino: iluminación localizada', lux: 1200 },
  { grupo: 'Metalúrgica', subtitulo: 'Talleres de montaje', tarea: 'Trabajo muy fino: instrumentos y mecanismos pequeños de precisión', lux: 2000 },
  { grupo: 'Metalúrgica', subtitulo: 'Talleres de montaje', tarea: 'Trabajo minucioso: iluminación localizada', lux: 3000 },
  { grupo: 'Metalúrgica', subtitulo: 'Depósito', tarea: 'Depósito de piezas sueltas y productos terminados', lux: 100 },
  { grupo: 'Metalúrgica', subtitulo: 'Áreas específicas', tarea: 'Mesas, ventanillas, etc', lux: 300 },
  { grupo: 'Metalúrgica', subtitulo: 'Elaboración de metales en láminas', tarea: 'Trabajo en banco y máquinas especiales', lux: 500 },
  { grupo: 'Metalúrgica', subtitulo: 'Máquinas y bancos de trabajo', tarea: 'Iluminación general', lux: 300 },
  { grupo: 'Metalúrgica', subtitulo: 'Máquinas y bancos de trabajo', tarea: 'Trabajo de piezas pequeñas en banco, rectificación de piezas medianas, herramientas', lux: 500 },
  { grupo: 'Metalúrgica', subtitulo: 'Máquinas y bancos de trabajo', tarea: 'Iluminación localizada para trabajos delicados, rectificación de precisión', lux: 1000 },
  { grupo: 'Metalúrgica', subtitulo: 'Máquinas y bancos de trabajo', tarea: 'Soldadura', lux: 300 },
  { grupo: 'Metalúrgica', subtitulo: 'Máquinas y bancos de trabajo', tarea: 'Tratamiento superficial de metales', lux: 300 },
  { grupo: 'Metalúrgica', subtitulo: 'Pintura', tarea: 'Preparación de los elementos', lux: 400 },
  { grupo: 'Metalúrgica', subtitulo: 'Pintura', tarea: 'Preparación, dosaje y mezcla de colores', lux: 1000 },
  { grupo: 'Metalúrgica', subtitulo: 'Pintura', tarea: 'Cabina de pulverización', lux: 400 },
  { grupo: 'Metalúrgica', subtitulo: 'Pintura', tarea: 'Pulido y terminación', lux: 600 },
  { grupo: 'Metalúrgica', subtitulo: 'Pintura', tarea: 'Inspección y retoque', lux: 600 },

  // Del Calzado
  { grupo: 'Del Calzado', subtitulo: '', tarea: 'Clasificación, marcado y corte', lux: 400 },
  { grupo: 'Del Calzado', subtitulo: '', tarea: 'Costura', lux: 600 },
  { grupo: 'Del Calzado', subtitulo: '', tarea: 'Inspección', lux: 1000 },

  // Centrales Eléctricas
  { grupo: 'Centrales Eléctricas', subtitulo: 'Estaciones de transformación exteriores', tarea: 'Circulación', lux: 100 },
  { grupo: 'Centrales Eléctricas', subtitulo: 'Estaciones de transformación exteriores', tarea: 'Locales de máquinas rotativas', lux: 200 },
  { grupo: 'Centrales Eléctricas', subtitulo: 'Equipos auxiliares', tarea: 'Máquinas estáticas, interruptores y otras', lux: 200 },
  { grupo: 'Centrales Eléctricas', subtitulo: 'Tableros de control y medición', tarea: 'Iluminación general', lux: 200 },
  { grupo: 'Centrales Eléctricas', subtitulo: 'Tableros de control y medición', tarea: 'Sobre el plano de lectura', lux: 400 },
  { grupo: 'Centrales Eléctricas', subtitulo: 'Subestaciones transformadoras', tarea: 'Exteriores', lux: 10 },
  { grupo: 'Centrales Eléctricas', subtitulo: 'Subestaciones transformadoras', tarea: 'Interiores', lux: 100 },

  // Cerámica
  { grupo: 'Cerámica', subtitulo: '', tarea: 'Preparación de las arcillas, amasado, molde, prensas, hornos y secadores', lux: 200 },
  { grupo: 'Cerámica', subtitulo: 'Barnizado y decoración', tarea: 'Trabajos finos', lux: 800 },
  { grupo: 'Cerámica', subtitulo: 'Barnizado y decoración', tarea: 'Trabajos medianos', lux: 400 },
  { grupo: 'Cerámica', subtitulo: 'Inspección', tarea: 'Iluminación localizada', lux: 1000 },

  // Del Cuero
  { grupo: 'Del Cuero', subtitulo: '', tarea: 'Limpieza, curtido, igualado del espesor, sobado, barnizado, secadores, terminación', lux: 200 },
  { grupo: 'Del Cuero', subtitulo: '', tarea: 'Inspección y trabajos especiales', lux: 600 },

  // Imprenta
  { grupo: 'Imprenta', subtitulo: 'Taller de tipografía', tarea: 'Iluminación general, compaginación, prensa para pruebas', lux: 300 },
  { grupo: 'Imprenta', subtitulo: 'Taller de tipografía', tarea: 'Mesa de correctores, pupitres para composición', lux: 800 },
  { grupo: 'Imprenta', subtitulo: 'Taller de linotipos', tarea: 'Iluminación general', lux: 300 },
  { grupo: 'Imprenta', subtitulo: 'Taller de linotipos', tarea: 'Sobre máquinas en la salida de letras y sobre el teclado', lux: 400 },
  { grupo: 'Imprenta', subtitulo: 'Taller de linotipos', tarea: 'Inspección de impresión de colores', lux: 1000 },
  { grupo: 'Imprenta', subtitulo: 'Rotativas', tarea: 'Tinteros y cilindros', lux: 300 },
  { grupo: 'Imprenta', subtitulo: 'Rotativas', tarea: 'Recepción', lux: 400 },
  { grupo: 'Imprenta', subtitulo: 'Grabado a mano', tarea: 'Iluminación localizada', lux: 1000 },
  { grupo: 'Imprenta', subtitulo: '', tarea: 'Litografía', lux: 700 },

  // Joyería y Relojería
  { grupo: 'Joyería y Relojería', subtitulo: 'Zona de trabajo', tarea: 'Iluminación general', lux: 400 },
  { grupo: 'Joyería y Relojería', subtitulo: 'Zona de trabajo', tarea: 'Trabajos finos', lux: 900 },
  { grupo: 'Joyería y Relojería', subtitulo: 'Zona de trabajo', tarea: 'Trabajos minuciosos', lux: 2000 },
  { grupo: 'Joyería y Relojería', subtitulo: 'Zona de trabajo', tarea: 'Corte de gemas, pulido y engarce', lux: 1300 },

  // Maderera
  { grupo: 'Maderera', subtitulo: 'Aserraderos', tarea: 'Iluminación general', lux: 100 },
  { grupo: 'Maderera', subtitulo: 'Aserraderos', tarea: 'Zona de corte y clasificación', lux: 200 },
  { grupo: 'Maderera', subtitulo: 'Carpintería', tarea: 'Iluminación general', lux: 100 },
  { grupo: 'Maderera', subtitulo: 'Carpintería', tarea: 'Zona de bancos y máquinas', lux: 300 },
  { grupo: 'Maderera', subtitulo: 'Carpintería', tarea: 'Trabajos de terminación de inspección', lux: 600 },
  { grupo: 'Maderera', subtitulo: 'Manufactura de muebles', tarea: 'Selección del enchapado y preparación', lux: 900 },
  { grupo: 'Maderera', subtitulo: 'Manufactura de muebles', tarea: 'Armado y terminación', lux: 400 },
  { grupo: 'Maderera', subtitulo: 'Manufactura de muebles', tarea: 'Marquetería', lux: 600 },
  { grupo: 'Maderera', subtitulo: 'Manufactura de muebles', tarea: 'Inspección', lux: 600 },

  // Papelera
  { grupo: 'Papelera', subtitulo: '', tarea: 'Local de máquinas', lux: 100 },
  { grupo: 'Papelera', subtitulo: '', tarea: 'Corte, terminación', lux: 300 },
  { grupo: 'Papelera', subtitulo: '', tarea: 'Inspección', lux: 500 },
  { grupo: 'Papelera', subtitulo: 'Manufacturas de cajas', tarea: 'Encartonado fijo', lux: 300 },
  { grupo: 'Papelera', subtitulo: 'Manufacturas de cajas', tarea: 'Cartones ordinarios, cajones', lux: 200 },

  // Química
  { grupo: 'Química', subtitulo: 'Planta de procesamiento', tarea: 'Circulación general', lux: 100 },
  { grupo: 'Química', subtitulo: 'Planta de procesamiento', tarea: 'Iluminación general sobre escaleras y pasarelas', lux: 200 },
  { grupo: 'Química', subtitulo: 'Sobre aparatos', tarea: 'Iluminación sobre plano vertical', lux: 200 },
  { grupo: 'Química', subtitulo: 'Sobre aparatos', tarea: 'Iluminación sobre mesas y pupitres', lux: 400 },
  { grupo: 'Química', subtitulo: 'Laboratorio de ensayo y control', tarea: 'Iluminación general', lux: 400 },
  { grupo: 'Química', subtitulo: 'Laboratorio de ensayo y control', tarea: 'Iluminación sobre el plano de lectura de aparatos', lux: 600 },
  { grupo: 'Química', subtitulo: 'Caucho', tarea: 'Preparación de la materia prima', lux: 200 },
  { grupo: 'Química', subtitulo: 'Caucho', tarea: 'Fabricación de neumáticos', lux: 200 },
  { grupo: 'Química', subtitulo: 'Caucho', tarea: 'Vulcanización de las envolturas y cámaras de aire', lux: 300 },
  { grupo: 'Química', subtitulo: 'Jabones', tarea: 'Iluminación general de las distintas operaciones', lux: 300 },
  { grupo: 'Química', subtitulo: 'Jabones', tarea: 'Panel de control', lux: 400 },
  { grupo: 'Química', subtitulo: 'Pinturas', tarea: 'Procesos automáticos', lux: 200 },
  { grupo: 'Química', subtitulo: 'Pinturas', tarea: 'Mezcla de pinturas', lux: 600 },
  { grupo: 'Química', subtitulo: 'Pinturas', tarea: 'Combinación de colores', lux: 1000 },
  { grupo: 'Química', subtitulo: 'Plásticos', tarea: 'Calandrado, extrusión, inyección, compresión y moldeado por soplado', lux: 300 },
  { grupo: 'Química', subtitulo: 'Plásticos', tarea: 'Fabricación de láminas, conformado, maquinado, fresado, pulido, cementado y recortado', lux: 400 },
  { grupo: 'Química', subtitulo: 'Depósito, almacenes y salas de empaque', tarea: 'Piezas grandes', lux: 100 },
  { grupo: 'Química', subtitulo: 'Depósito, almacenes y salas de empaque', tarea: 'Piezas pequeñas', lux: 200 },
  { grupo: 'Química', subtitulo: 'Depósito, almacenes y salas de empaque', tarea: 'Expedición de mercaderías', lux: 300 },

  // Del Tabaco
  { grupo: 'Del Tabaco', subtitulo: '', tarea: 'Proceso completo', lux: 400 },

  // Textil
  { grupo: 'Textil', subtitulo: 'Tejidos de algodón y lino', tarea: 'Mezcla, cardado, estirado, torcido, peinado, hilado', lux: 200 },
  { grupo: 'Textil', subtitulo: 'Urdimbre', tarea: 'Sobre los peines', lux: 700 },
  { grupo: 'Textil', subtitulo: 'Tejido', tarea: 'Telas claras y medianas', lux: 400 },
  { grupo: 'Textil', subtitulo: 'Tejido', tarea: 'Telas oscuras', lux: 700 },
  { grupo: 'Textil', subtitulo: 'Inspección', tarea: 'Telas claras y medianas', lux: 600 },
  { grupo: 'Textil', subtitulo: 'Inspección', tarea: 'Telas oscuras', lux: 900 },
  { grupo: 'Textil', subtitulo: 'Lana', tarea: 'Cardado, lavado, peinado, retorcido, tintura, urdimbre', lux: 200 },
  { grupo: 'Textil', subtitulo: 'Tejidos de lana', tarea: 'Telas claras y medianas', lux: 600 },
  { grupo: 'Textil', subtitulo: 'Tejidos de lana', tarea: 'Telas oscuras / Máquinas de tejidos de punto', lux: 900 },
  { grupo: 'Textil', subtitulo: 'Inspección de lana', tarea: 'Telas claras y medianas', lux: 1200 },
  { grupo: 'Textil', subtitulo: 'Inspección de lana', tarea: 'Telas oscuras', lux: 1500 },
  { grupo: 'Textil', subtitulo: 'Seda natural y sintética', tarea: 'Embebido, teñido y texturado', lux: 300 },
  { grupo: 'Textil', subtitulo: 'Seda natural y sintética', tarea: 'Hilado', lux: 450 },
  { grupo: 'Textil', subtitulo: 'Seda natural y sintética', tarea: 'Urdimbre', lux: 700 },
  { grupo: 'Textil', subtitulo: 'Yute', tarea: 'Hilado, tejido con lanzaderas, devanado, calandrado', lux: 200 },

  // Del Vestido
  { grupo: 'Del Vestido', subtitulo: 'Sombreros', tarea: 'Limpieza, tintura, terminación, forma, alisado, planchado', lux: 400 },
  { grupo: 'Del Vestido', subtitulo: 'Sombreros', tarea: 'Costura', lux: 600 },
  { grupo: 'Del Vestido', subtitulo: 'Vestimenta', tarea: 'Sobre máquinas', lux: 600 },
  { grupo: 'Del Vestido', subtitulo: 'Vestimenta', tarea: 'Manual', lux: 800 },
  { grupo: 'Del Vestido', subtitulo: 'Fábrica de guantes', tarea: 'Prensa, tejidos, muestreo, corte', lux: 400 },
  { grupo: 'Del Vestido', subtitulo: 'Fábrica de guantes', tarea: 'Costura', lux: 600 },
  { grupo: 'Del Vestido', subtitulo: 'Fábrica de guantes', tarea: 'Control', lux: 1000 },

  // Del Vidrio
  { grupo: 'Del Vidrio', subtitulo: 'Sala de mezclado', tarea: 'Iluminación general', lux: 200 },
  { grupo: 'Del Vidrio', subtitulo: 'Sala de mezclado', tarea: 'Zona de dosificación', lux: 400 },
  { grupo: 'Del Vidrio', subtitulo: 'Sala de mezclado', tarea: 'Local de horno', lux: 100 },
  { grupo: 'Del Vidrio', subtitulo: 'Local de manufactura mecánica', tarea: 'Sobre máquinas: Iluminación general', lux: 200 },
  { grupo: 'Del Vidrio', subtitulo: 'Manual', tarea: 'Iluminación general / Terminación general', lux: 200 },
  { grupo: 'Del Vidrio', subtitulo: 'Manual', tarea: 'Corte, pulido y biselado', lux: 400 },
  { grupo: 'Del Vidrio', subtitulo: 'Inspección', tarea: 'General', lux: 400 }
];
